services:
  db:
    image: postgres:16.3-alpine3.20
    container_name: k_gen_database
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: safepassword
    volumes:
     - k_gen_database_vol:/var/lib/postgresql/data
     - type: bind
       source: ./sql/
       target: /docker-entrypoint-initdb.d/
    ports:
      - "5444:5432"

  frontend:
    image: node:18-alpine
    container_name: k_gen_frontend
    working_dir: /frontend
    volumes:
     - type: bind
       source: ./frontend/
       target: /frontend
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    command: npm run dev

  backend:
    image: golang:1.22.5-alpine3.20
    container_name: k_gen_backend
    restart: always
    working_dir: /backend
    volumes:
     - type: bind
       source: ./backend/
       target: /backend
    command: ["go", "run", "main.go"]
    environment:
      DOCKER_DB_URL: postgres://postgres:safepassword@db:5432/cl-database
    ports:
      - "8083:8082"
    depends_on:
      - db

volumes:
  k_gen_database_vol: